-- AlterTable
ALTER TABLE "project" ALTER COLUMN "startDate" SET DATA TYPE TEXT,
ALTER COLUMN "approvalDate" DROP DEFAULT,
ALTER COLUMN "approvalDate" SET DATA TYPE TEXT,
ALTER COLUMN "endDate" SET DATA TYPE TEXT;
